version: "3"

services:
  celestia:
    image: ghcr.io/rollkit/local-celestia-devnet:v0.10.0
    restart: unless-stopped
    expose:
      - "26657"
      - "26659"
    # Rollup can't start until after DA starts.
    # This ensures it waits 5 seconds so the rollup can query it.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:26657/block?height=1"]
      interval: 5s
      timeout: 10s
      retries: 5
  gm:
    build:
      context: .
      dockerfile: split.Dockerfile
    restart: unless-stopped
    expose:
      - "26658"
    environment:
      - RPC=http://celestia:26657/
      - START_ARGS=--rollkit.aggregator
    volumes:
      - config:/home/rollkit/.gm
    # healthcheck:
    #   test: ["CMD", "nc", "-zv", "localhost", "26658"]
    #   interval: 5s
    #   timeout: 10s
    #   retries: 5
  rollkit:
    image: ghcr.io/rollkit/rollkit:local
    restart: unless-stopped
    command: node --proxy_app=tcp://gm:26658 --rpc.laddr=tcp://0.0.0.0:26657 --rollkit.aggregator=true --rollkit.da_layer=celestia --rollkit.da_config='{"base_url":"http://celestia:26659","timeout":60000000000,"fee":6000,"gas_limit":6000000}' --rollkit.namespace_id=f5536d1ea2373df7 --rollkit.da_start_height=0
    volumes:
      - config:/home/rollkit/.rollkit
    depends_on:
      celestia:
        condition: service_healthy
      # gm:
      #   condition: service_healthy

volumes:
  config:
